apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: wcza3scpl-python 
  janus-idp.io/tekton: wcza3scpl-python
  backstage.io/kubernetes-id: wcza3scpl-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wcza3scpl-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml